### PR TITLE
Merge `dev`

### LINKED ISSUE #4379: Merge dev to feat-2.0

### PR DESCRIPTION
**Pull request by Fraser999**
This PR merges `dev` into `feat-2.0`.

There were many conflicts, with the more significant ones being around:
* the auction in EE
* the `advance_era` and similar methods of `WasmTestBuilder`
* the `BlockValidator` (generally the changes from `dev` were used as this component still has to be updated on `feat-2.0` to handle `Transaction`s properly)
* the `Storage` component (mainly related to handling execution results)
* the main_reactor tests (three new tests and related helper functions added in `feat-2.0` were rewritten to use the updated test fixture provided in `dev` - total runtime dropped from 5.5mins to 36secs)

Closes #4379.

### CODE REVIEW

**Review by alsrdn — APPROVED** [review]
LGTM

**Comment by Fraser999** [comment]
bors merge

**Comment by Fraser999** [comment]
bors merge

**Comment by Fraser999** [comment]
bors merge

**Comment by Fraser999** [comment]
bors merge

**Pull request merged**
