### PR TITLE
(feat-rocksdb) Adds backward-compatible resumption safety to lmdb migration

### PR DESCRIPTION
**Pull request by dwerner**
This PR fixes resumption-safety in the lmdb-rocksdb migration in a backward-compatible way with the existing column family used to track migration.

### CODE REVIEW

**Review by xcthulhu — APPROVED** [review]

**Comment by dwerner** [comment]
bors merge

**Comment by dwerner** [comment]
bors merge

**Comment by dwerner** [comment]
bors merge

**Comment by dwerner** [comment]
bors merge

**Pull request merged**
