### PR TITLE
Update obsolete URLs in Readme - PR for #337

### PR DESCRIPTION
**Pull request by devendran-m**
Please consider the following when creating a PR:

This is a PR for updates to the Readme file where obsolete/broken URLs/links under the below sections were replaced with recent/relevant updated links;

**Reason for change/update:**  After redirecting the documentation from https://casper.network/docs to https://docs.casperlabs.io/, the following sections of the README file needs updating to updated/relevant links;

**Update 1:** 
Hyperlink in Platform Specification from https://docs.casperlabs.io/en/latest/implementation/index.html to https://docs.casperlabs.io/design/

**Update 2:** 

Hyperlink of "Writing Smart Contracts" in the 'Getting started with smart contracts' section of the [README.md](https://github.com/casper-network/casper-node#get-started-with-smart-contracts) needs fixing.  
Currently, the underlying link/URL is - https://docs.casperlabs.io/en/latest/dapp-dev-guide/index.html. It needs to be updated to https://docs.casperlabs.io/dapp-dev-guide/
 
Link to the GitHub issue relating to this PR;
https://github.com/casper-network/docs/issues/337

### CODE REVIEW

**Review by ipopescu — APPROVED** [review]
Thanks, @devendran-m! LGTM

**Review by darthsiroftardis — APPROVED** [review]

**Comment by ipopescu** [comment]
@bradjohnl do you know what needs to happen here so we can merge? Thank you!

**Comment by bradjohnl** [comment]
> @bradjohnl do you know what needs to happen here so we can merge? Thank you!

This PR is on the casper-node repo, so you need to use bors:https://casperlabs.atlassian.net/wiki/spaces/EN/pages/95748224/How+To+Bors

**Comment by ipopescu** [comment]
@bradjohnl one more question about this (sorry!): how do I trigger the linter? The bors failed due to lints not having run.

**Comment by bradjohnl** [comment]
@ipopescu @TomVasile 

There is a GH Action workflow that is required but does not trigger for .md files. The result of this is that the step does not get executed.

The workflow needs to be changed to accomodate the PRs that target .md files only.
https://github.com/casper-network/casper-node/blob/dev/.github/workflows/lints.yml

 I think these "path-ignore" elements should be removed:
```
on:
  push:
    branches:
      - dev
      - trying
      - staging
      - 'release-**'
      - 'feat-**'
    paths-ignore:
      - '**.md'

  pull_request:
    branches:
      - dev
      - 'release-**'
      - 'feat-**'
    paths-ignore:
      - '**.md'
```

Or alternatively maybe it's possible to exclude this requirements for md files? BTW you can lint md files as well afaik.

**Comment by ipopescu** [comment]
Thanks, @bradjohnl. So, this PR will be blocked until the workflow gets updated for .md files.
I don't usually use a linter for .md files although I am sure it is useful in some cases. 
In this case, what would be the quickest path to resolution? Excluding the linter for .md files is ok IMO.

**Pull request merged**
