### PR TITLE
Fixes integer overflow in `u8_slice_to_bytes`.

### LINKED ISSUE #2260: Fix integer overflow in u8_slice_to_bytes.
Instead of a conversion using as, prefer the TryFrom trait in https://github.com/casper-network/casper-node/blob/release-1.3.4/types/src/bytesrepr.rs#L1100

### PR DESCRIPTION
**Pull request by luis-casper**
Introduces a new variant of `ApiError`.

Closes #2260

### CODE REVIEW

**Review by dwerner — APPROVED** [review]
Looks good to me, but wait for an another review from @Fraser999 or others.

**Review by Fraser999 — CHANGES_REQUESTED** [review]
This LGTM so far, but I'm blocking this until you have a chance to check for any other such instances in the codebase.

Also, please update the changelog in this PR too.

**Comment by luis-casper** [comment]
> This LGTM so far, but I'm blocking this until you have a chance to check for any other such instances in the codebase.

I wasn't very clear, but this has been done.

**Comment by mpapierski** [comment]
Closing in favor of #2602

**Pull request closed without merging**
