### PR TITLE
(feat-2.0) - Remove K,V generics from the trie

### PR DESCRIPTION
**Pull request by dwerner**
This PR removes much incidental complexity arising from making K and V arguments to trie methods generic, when in reality we rarely use this generality, and moreover only in unit tests.

In addition, we now make use of `DataAccessLayer`, which uses `ScratchGlobalState`, which wraps `LmdbGlobalState`. This is an intermediate refactoring step to reduce the unnecessary complexity in the trie implementation.

Going forward, we can build on this work by collapsing LmdbGlobalState and ScratchGlobalState together into a cache-aware type.

This PR also integrates cache/scratch semantics into exec/commit.

Execute + commit is now replaced by `exec` + `apply` (commits to cache), + `commit_to_disk`.

This PR also refactors WasmTestBuilder to remove it's generality related to tries and EngineState, and also integrates ScratchGlobalState more closely.

### CODE REVIEW

**Review by georgepisaltu — APPROVED** [review]
Some tests failing with the "cannot start era with total weight 0", most likely slipped during the merge as it didn't trigger a conflict. Other than that, PR looks great to me!

**Comment by dwerner** [comment]
bors try

**Comment by dwerner** [comment]
bors try

**Comment by dwerner** [comment]
bors try

**Comment by dwerner** [comment]
bors try

**Comment by ghost** [comment]
continuous-integration/drone/pr — Build is failing 
https://drone-auto-casper-network.casperlabs.io/casper-network/casper-node/7419

Get a 404 error

**Comment by dwerner** [comment]
stale

**Pull request closed without merging**
