### PR TITLE
Native auction support for data_provider

### PR DESCRIPTION
**Pull request by EdHastingsCasperAssociation**
This PR adds `step`, `fee` and `block_rewards` support to data provider.

### CODE REVIEW

**Comment by AlexanderLimonov** [comment]
Unlike in the CI run, I was able to merge this into `feat-2.0` without conflicts but it appears to subtly break reward distribution (typical error below), so we'll have to investigate further

`
---- reactor::main_reactor::tests::run_reward_network_zug_no_finality_small_nominal_five_eras stdout ----
thread 'reactor::main_reactor::tests::run_reward_network_zug_no_finality_small_nominal_five_eras' panicked at 'assertion failed: ``(left == right)``
  left: ``Ratio { numer: 111328978001147, denom: 1 }``,
 right: ``Ratio { numer: 102051563167721, denom: 1 }``: total supply does not match at height 10', node/src/reactor/main_reactor/tests.rs:2122:13
`

**Comment by EdHastingsCasperAssociation** [comment]
> Unlike in the CI run, I was able to merge this into feat-2.0 without conflicts but it appears to subtly break reward distribution...

ill try to reproduce locally

**Comment by EdHastingsCasperAssociation** [comment]
>  so we'll have to investigate further

Got w/ @fizyk20 and we figured it out...distribute is self commiting but its effects were getting added to the transaction effects and getting commited a second time. we should discuss if distribute should self commit or not, but for now we'll leave it auto-commit and not include its effects with the transaction effects.

**Review by AlexanderLimonov — APPROVED** [review]
Other than maybe values for reactor rewards test maybe being on the low side (see CI failure), no objections from me, everything looks good

**Review by fizyk20 — APPROVED** [review]
TBH, I find it a bit weird that system contract functionality is now a part of the storage layer - it feels more like something that should be built on top of the storage layer, rather than be a part of it, but I assume this has been discussed and a decision has been made to structure it like this.

Other than that, looks good to me :+1:

**Comment by EdHastingsCasperAssociation** [comment]
we could put it in another crate for organizational purposes but functionally its really just global state management logic. global state lived in the ee crate for legacy reasons, thus this logic lived there too. we've now moved global state into a separate crate and this logic is moving with it.

**Review by darthsiroftardis — APPROVED** [review]

**Pull request merged**
