### PR TITLE
Avoid announcing `DeployExpired` for executed deploys

### LINKED ISSUE #3696: Joining node incorrectly emitting `DeployExpired` events
While eyeballing the event stream of a node joining a testnet, there were `DeployExpired` events emitted for deploys which were also included in a block

### PR DESCRIPTION
**Pull request by Fraser999**
This PR fixes an issue in the `DeployBuffer` where all purged deploys were announced as expired.  Now only those which are not in the `dead` collection are announced.

Closes #3696.

### CODE REVIEW

**Review by georgepisaltu — APPROVED** [review]

**Review by rafal-ch — APPROVED** [review]
LGTM :+1:

**Pull request merged**
