### PR TITLE
CI: run nightly for release 1.5.0

### PR DESCRIPTION
**Pull request by TomVasile**
Changes:
- adds cron job for running nightly nctl tests
- syncs changes from https://github.com/casper-network/casper-node/pull/2925
    - adjusted `ci.json` for release-1.5.0

Ticket: https://app.zenhub.com/workspaces/cn-sre-60d363546afb85000e491ff6/issues/casper-network/sre/414

### CODE REVIEW

**Review by sacherjj — APPROVED** [review]

**Comment by sacherjj** [comment]
Wonder if we want to include release-1.4.6 in this for short time.

**Comment by TomVasile** [comment]
> Wonder if we want to include release-1.4.6 in this for short time.

to come :)

**Comment by TomVasile** [comment]
bors try

**Comment by TomVasile** [comment]
1.5.0 was merged back to dev, these changes already exist there.

**Pull request closed without merging**
