### PR TITLE
Change the base ports for all services of nctl nodes

### PR DESCRIPTION
**Pull request by marc-casperlabs**
See https://github.com/casper-network/casper-node/issues/1478#issuecomment-858592003 for details.

### CODE REVIEW

**Comment by TomVasile** [comment]
bors try

**Comment by marc-casperlabs** [comment]
bors try

**Review by TomVasile — APPROVED** [review]
Looped it all day no problem. Greenlight from my side 👍 . 

I'll let @momipsl chime in on any other downstream side effects.

**Comment by marc-casperlabs** [comment]
I've had a chance to ask @momipsl about this and he seems cautiously optimistic. Merging this!

bors r+

**Pull request merged**
