### PR TITLE
NCTL: ports changes from dev

### PR DESCRIPTION
**Pull request by TomVasile**
This PR is a port of https://github.com/casper-network/casper-node/pull/1719 & https://github.com/casper-network/casper-node/pull/1722 from [dev](https://github.com/casper-network/casper-node/tree/dev.).

This PR makes **NO** code changes to casper-node. The changes are solely NCTL/CI based.

### CODE REVIEW

**Comment by TomVasile** [comment]
bors try

**Review by sacherjj — APPROVED** [review]

**Pull request merged**
