### PR TITLE
Porting old 1.6 prs

### PR DESCRIPTION
**Pull request by mpapierski**
This PR is cherry-picking the following PRs that were previously merged into `feat-1.6` branch

- #3967
- #3978, but it turns out it was noop as it was likely ported in #4732 
- #4082 and #4305

### CODE REVIEW

**Comment by sacherjj** [comment]
Just using as a test for CI working

**Comment by sacherjj** [comment]
bors try

**Review by EdHastingsCasperAssociation — APPROVED** [review]

**Pull request merged**
