### PR TITLE
Move NCTL to a separate repo

### PR DESCRIPTION
**Pull request by jacek-casper**
This PR extracts NCTL code and pulls it from https://github.com/casper-network/casper-nctl for CI.

There are no major changes other than the repository being different. It needs to be cloned and placed next to the existing project directories. The CI is still set up in the casper-node repo.
Some things you might need to do manually when switching:
- update the bashrc or any other shell rc file you use with the new path to the activate script (https://github.com/casper-network/casper-nctl/blob/dev/docs/setup.md#extend-bashrc-file-to-make-nctl-commands-available-from-terminal-session)
- stop any existing NCTL network before you switch (nctl-stop)

### CODE REVIEW

**Comment by jacek-casper** [comment]
bors try

**Comment by jacek-casper** [comment]
bors try

**Review by EdHastingsCasperAssociation — APPROVED** [review]

**Comment by jacek-casper** [comment]
bors try

**Comment by jacek-casper** [comment]
bors single on

**Pull request merged**
