### PR TITLE
Check the immediate caller in system contracts.

### PR DESCRIPTION
**Pull request by mpapierski**
Checks if immediate caller is of session type of the same account as the provided account hash.

### CODE REVIEW

**Review by darthsiroftardis — APPROVED** [review]

**Review by luis-casper — APPROVED** [review]
Looks good to me.
It should be noted that each of the affected auction functions now have a public key parameter that is unneeded: it could be understood that the account controlling the session is what the parameter used to represent.

**Comment by sacherjj** [comment]
> Looks good to me. It should be noted that each of the affected auction functions now have a public key parameter that is unneeded: it could be understood that the account controlling the session is what the parameter used to represent.

Should capture this as a tech debt ticket?

**Comment by mpapierski** [comment]
> 
> 
> > Looks good to me. It should be noted that each of the affected auction functions now have a public key parameter that is unneeded: it could be understood that the account controlling the session is what the parameter used to represent.
> 
> Should capture this as a tech debt ticket?

I don't think we can realistically address this as long as we either use account hashes on EE side, or public keys on the consensus side. Will be ticketed to not forget about this

**Comment by sacherjj** [comment]
bors try

**Pull request merged**
