### PR TITLE
Fix invalid cancel_reservations args

### PR DESCRIPTION
**Pull request by wojcik91**
Fix `cancel_reservations` args typing in remaining places.

### CODE REVIEW

**Comment by wojcik91** [comment]
resolves https://github.com/casper-network/casper-node/issues/5006

**Review by EdHastingsCasperAssociation — APPROVED** [review]

**Comment by davidatwhiletrue** [comment]
@wojcik91 there seems to be still a mismatch between expected arguments at different layers.

Here, the node is looking for `delegator_kinds` input argument:

https://github.com/teonite/casper-node/blob/122bbe995ae4f2ef817238c010ba40487d242ba9/storage/src/data_access_layer/auction.rs#L310

I guess it should be `delegators` instead to match auction contract interface.

**Comment by wojcik91** [comment]
> @wojcik91 there seems to be still a mismatch between expected arguments at different layers.
> 
> Here, the node is looking for `delegator_kinds` input argument:
> 
> https://github.com/teonite/casper-node/blob/122bbe995ae4f2ef817238c010ba40487d242ba9/storage/src/data_access_layer/auction.rs#L310
> 
> I guess it should be `delegators` instead to match auction contract interface.

That's correct, thanks for pointing it out.

**Pull request merged**
