### PR TITLE
Do not use oneshot senders for HTTP server shutdowns

### LINKED ISSUE #3399: Refactor out oneshot senders
The node has historically used oneshot channels as means to coordinate shutdowns between background tasks where necessary. This functionality has been implemented in a cleaner fashion in the 1.6 tree through the use of fuses (specifically DropSwitch<ObservableFuse>).
Removing all uses of oneshot::channel::<()> and replacing it with the pattern described above will make the code a little shorter and easier to understand for others diving in.

### PR DESCRIPTION
**Pull request by marc-casperlabs**
Closes #3399.

This ports all warp based servers, which were the last holdouts, to use the `ObservableFuse` instead of `tokio::sync::oneshot` channels.

### CODE REVIEW

**Review by Fraser999 — APPROVED** [review]

**Comment by Fraser999** [comment]
bors merge

**Comment by Fraser999** [comment]
bors merge

**Review by rafal-ch — APPROVED** [review]
LGTM :+1:

**Pull request merged**
