### PR TITLE
Fix npm audit issues

### LINKED ISSUE #1802: Add npm audit to CI
Add an `npm audit` step to CI with a path filter to trigger only when an AssemblyScript code is changed.

### PR DESCRIPTION
**Pull request by mpapierski**
Closes #1802 #1803

Adds unconditional `npm audit` to CI, and resolves audited vulnerabilities for 3rd party packages by using `npm-force-resolutions`

### CODE REVIEW

**Review by luis-casper — APPROVED** [review]

**Review by Fraser999 — APPROVED** [review]
Approved, but I think it might be worth renaming the `cargo-audit` target in .drone.yml?

Maybe @sacherjj or @TomVasile have a preference, but I'd suggest either just `audit` or `cargo-and-npm-audit`

**Review by hoffmannjan — APPROVED** [review]

**Comment by mpapierski** [comment]
> Approved, but I think it might be worth renaming the `cargo-audit` target in .drone.yml?
> 
> Maybe @sacherjj or @TomVasile have a preference, but I'd suggest either just `audit` or `cargo-and-npm-audit`

Renamed to `audit`

**Pull request closed without merging**
