### PR TITLE
Amend ContractPackage string prefix

### LINKED ISSUE #2257: Amend ContractPackage string prefix and analyse impact of change
The contract package string prefix is incorrect and should be changed to contract-package-. However, this may well have severe downstream impacts (i.e NOT ON THE NODE) should be analysed, to discover if there any breaking changes. This includes but is not limited to:

- rpc api
- event stream data and things that use it
- all SDK's for instance
- any direct wire up like curl statements etc

### PR DESCRIPTION
**Pull request by HansWestman74**
* Added PACKAGE_STRING_PREFIX_LEGACY: &str = "contract-package-wasm"
* Changed PAKCAGE_STRING_PREFIX from "contract-package-wasm" to  "contract-package";
* Changed ContractPackageHash::from_formatted_str (&formatted_string) to accept Legacy prefix.
* Wrote test should_accept_legacy_and_new_package_prefix() that verifies that the latest from_formatted_str function works with  both legacy and new prefix.

closes #2257

### CODE REVIEW

**Comment by goral09** [comment]
Needs a CHANGELOG entry.

**Review by Fraser999 — CHANGES_REQUESTED** [review]
I opened https://github.com/HansWestman74/casper-node-1/pull/3 to address what would have been my review comments.

Blocking for now as `PACKAGE_STRING_PREFIX` in this PR is currently incorrect.

**Review by Fraser999 — APPROVED** [review]
Do we need the changes to `smart_contracts/contract_as/package-lock.json`?  If not, please revert them.

Otherwise LGTM.

**Comment by cspramit** [comment]
@HansWestman74 what is impact? specifically downstream

**Review by Fraser999 — APPROVED** [review]

**Comment by HansWestman74** [comment]
bors merge

**Pull request merged**
