### PR TITLE
dead link fix

### PR DESCRIPTION
**Pull request by cspramit**
Please consider the following when creating a PR:

* Fix operator link

### CODE REVIEW

**Review by sacherjj — APPROVED** [review]

**Review by rafal-ch — APPROVED** [review]
LGTM :+1:

**Comment by cspramit** [comment]
bors merge

**Review by EdHastingsCasperAssociation — APPROVED** [review]

**Comment by sacherjj** [comment]
bors merge

**Comment by cspramit** [comment]
bors merge

**Comment by dwerner** [comment]
bors merge

**Comment by Fraser999** [comment]
bors merge

**Pull request merged**
