### PR TITLE
Fix upgrade test issues in 2.0

### PR DESCRIPTION
**Pull request by jacek-casper**
Needed to adjust
- post-upgrade block parsing
- starting up the sidecar in upgrade_from_stage_single_node.sh
- counting the nodes while excluding sidecars

### CODE REVIEW

**Review by rafal-ch — APPROVED** [review]
LGTM :+1:

**Review by alsrdn — APPROVED** [review]

**Comment by alsrdn** [comment]
bors merge

**Comment by alsrdn** [comment]
bors merge

**Pull request merged**
