### PR TITLE
Speculative config changes to help reactor rewards tests pass

### PR DESCRIPTION
**Pull request by AlexanderLimonov**
See https://github.com/casper-network/casper-node/pull/4433 and https://github.com/casper-network/casper-node/pull/4446

Ticket https://github.com/casper-network/casper-node/issues/4401

### CODE REVIEW

**Review by EdHastingsCasperAssociation — APPROVED** [review]

**Review by fizyk20 — APPROVED** [review]

**Comment by AlexanderLimonov** [comment]
bors merge

**Comment by AlexanderLimonov** [comment]
bors merge

**Comment by AlexanderLimonov** [comment]
bors merge

**Comment by AlexanderLimonov** [comment]
bors merge

**Comment by AlexanderLimonov** [comment]
bors merge

**Comment by AlexanderLimonov** [comment]
bors merge

**Comment by AlexanderLimonov** [comment]
bors merge

**Comment by AlexanderLimonov** [comment]
bors merge

**Comment by AlexanderLimonov** [comment]
bors merge

**Comment by AlexanderLimonov** [comment]
bors merge

**Comment by AlexanderLimonov** [comment]
bors merge

**Pull request merged**
