### PR TITLE
Add Zug consensus protocol

### PR DESCRIPTION
**Pull request by afck**
This allows choosing one of two consensus protocols in the chainspec, Zug or Highway.

Zug is a very simple leader-based partially synchronous protocol:
* In every round, the leader proposes a block (with some hash `h`). If a quorum of validators signs `Echo(h)`, it becomes that round's unique accepted candidate. If a quorum signs `Vote(true)`, the block and all its ancestors get finalized.
* If a quorum signs `Vote(false)`, the next round's leader is allowed to propose a block whose parent is _not_ `h`. If there is a quorum of `Echo(h)`, the next round's leader is allowed to propose a block whose parent _is_ `h`. (Both can be the case!)
* Validators vote `true` only after seeing a quorum of `Echo`es with matching hash. They vote `false` if they time out waiting for that.

A detailed description is in [this paper](https://arxiv.org/abs/2205.06314), using the gossiping variant (i.e. section 6.2, not 6.1).

Instead of the Highway round exponent, a more explicit `minimum_block_time` can now be configured and applies to both protocols.

There are still a few TODOs, and the tests should be expanded, but it has been successfully tried out in a local network.

This is a backport of https://github.com/casper-network/casper-node/pull/3362.

Closes  https://github.com/casper-network/Governance/issues/310.

### CODE REVIEW

**Comment by afck** [comment]
bors try

**Comment by afck** [comment]
bors try

**Comment by afck** [comment]
bors try

**Comment by afck** [comment]
bors try

**Review by fizyk20 — APPROVED** [review]
LGTM :+1:

**Review by EdHastingsCasperAssociation — APPROVED** [review]
I skimmed it and it looks good superficially. I defer to the SME's and we'll deal w/ any issues that arise after merge.

**Pull request merged**
