### PR TITLE
restore removed rpc schema

### PR DESCRIPTION
**Pull request by gyroflaw**
Closes https://github.com/casper-network/casper-node/issues/4594

File was recovered from https://github.com/casper-network/casper-node/blob/b08f3cb722a5b594564c7cad291006a3a3ad7630/resources/test/rpc_schema.json

### CODE REVIEW

**Comment by EdHastingsCasperAssociation** [comment]
the json rpc isn't in the node anymore...it's in the sidecar now and the schema discovery for it should also live there. @jacek-casper

**Comment by jacek-casper** [comment]
@gyroflaw 
Yes, the schema and the RPC have been moved to this repo: https://github.com/casper-network/casper-sidecar

**Comment by gyroflaw** [comment]
> @gyroflaw Yes, the schema and the RPC have been moved to this repo: https://github.com/casper-network/casper-sidecar

thank you for your reply, then where can I find the rpc schema file?

**Comment by jacek-casper** [comment]
@gyroflaw here: https://github.com/casper-network/casper-sidecar/blob/feat-2.0/resources/test/schema_rpc_schema.json

**Pull request closed without merging**
