### PR TITLE
CI: add markdown link checking

### PR DESCRIPTION
**Pull request by TomVasile**
Changes:
- adds `ci/markdown_link_check.sh` & `ci/markdown_link_check.sh`
- adds `markdown-link-check` step to CI

### CODE REVIEW

**Comment by TomVasile** [comment]
Currently failing:
```
FILE: ./execution_engine/src/shared/logging/README.md | 217s

189 | ERROR: 4 dead links found! | 219s
190 | [✖] https://docs.rs/casper-engine-shared/latest/casper_engine_shared/logging/fn.initialize.html → Status: 404 | 219s
191 | [✖] https://docs.rs/casper-engine-shared/latest/casper_engine_shared/logging/fn.log_metric.html → Status: 404 | 219s
192 | [✖] https://docs.rs/casper-engine-shared/latest/casper_engine_shared/logging/fn.log_duration.html → Status: 404 | 219s
193 | [✖] https://github.com/CasperLabs/CasperLabs/tree/master/execution-engine/engine-metrics-scraper → Status: 404
```

**Comment by TomVasile** [comment]
spoke with Fraser, both `casper_engine_shared` and `engine-metrics-scraper` are no longer maintained or published. I'll rip these out.

**Review by Fraser999 — APPROVED** [review]

**Pull request merged**
