### PR TITLE
Reference counted network messages

### PR DESCRIPTION
**Pull request by marc-casperlabs**
This removes the in-memory copying of outgoing network messages, saving a substantial amount of memory in the case of broadcasts and, to some extent, gossips.

Splits the formerly symmetrical networking transport into an outgoing one that shares references, while the incoming stream is still value based.

### CODE REVIEW

**Review by goral09 — APPROVED** [review]
The code looks good, I assume you've run it and tested.

**Comment by marc-casperlabs** [comment]
> The code looks good, I assume you've run it and tested.

Yes, tests and one `nctl` run.

**Review by Fraser999 — APPROVED** [review]
LGTM!

**Pull request merged**
