### PR TITLE
Fix an issue in StateProvider::addressable_entity

### PR DESCRIPTION
**Pull request by jacek-casper**
The existing lookup is broken, the addressable entity key it finds gets discarded because of a semicolon at the end of the `if`, so the existing code always falls through into the `expected a CLValue::Key or Account to be stored under account hash` case. Interestingly no test seems to cover this

### CODE REVIEW

**Comment by jacek-casper** [comment]
bors try

**Review by darthsiroftardis — APPROVED** [review]

**Comment by jacek-casper** [comment]
bors try

**Comment by jacek-casper** [comment]
borse r+

**Comment by jacek-casper** [comment]
fix has already been applied to feat-2.0, closing

**Pull request closed without merging**
