### PR TITLE
Remove logic for upgrade of withdrawal purses

### LINKED ISSUE #2479: Remove upgrade logic for withdraw/unbonding purses
https://github.com/casper-network/casper-node/pull/2440#discussion_r766985457

### PR DESCRIPTION
**Pull request by darthsiroftardis**
CHANGELOG:

- Removed logic in `commit_upgrade` that transformed withdraw purses into unbonding purses
- Removed two tests that would exercise the now-removed upgrade logic

Closes #2479

### CODE REVIEW

**Review by goral09 — APPROVED** [review]

**Comment by goral09** [comment]
We're waiting with the merge for after the 1.5.0.

**Review by Fraser999 — APPROVED** [review]

**Comment by cspramit** [comment]
why free floating PR?

**Comment by Fraser999** [comment]
@cspramit It's already linked to https://github.com/casper-network/casper-node/issues/2479 by the looks of it?

**Pull request merged**
