### PR TITLE
Bumping to 1.3.1 and disable dependabot

### PR DESCRIPTION
**Pull request by sacherjj**
Bumping version to 1.3.1
Removed the dependabot.yml file to disable once this is the default branch.

### CODE REVIEW

**Review by nilz3ro — APPROVED** [review]
LGTM 🎊

**Review by Fraser999 — APPROVED** [review]

**Comment by sacherjj** [comment]
bors merge

**Comment by sacherjj** [comment]
Did bors just lose this after staging?

**Comment by sacherjj** [comment]
bors merge

**Comment by sacherjj** [comment]
bors merge

**Pull request merged**
