### PR TITLE
NCTL :: Fixed inline python issue + increased initial balances.

### PR DESCRIPTION
**Pull request by ghost**
1. Increased initial balances due to recent "economics" changes.
2. Fixed inline python issue reported by @George-cl.

### CODE REVIEW

**Review by Fraser999 — APPROVED** [review]

**Review by George-cl — APPROVED** [review]
Looks good - shame you have to have them as one-liners for it to work.

**Review by linclelinkpart5 — APPROVED** [review]
Looks good to me! Wish the multiline Python worked, it looks so much nicer

**Pull request merged**
