### PR TITLE
Caller extension

### PR DESCRIPTION
**Pull request by darthsiroftardis**
CHANGELOG:

- Fixed wire up for FFI `load_call_stack` into the runtime to keep it backwards compatible
- Added regression test suite to ensure migrated 1.x Wasm can still load and peek the call stack
- Added a new FFI method that returns, the initiator of the call chain, immediate caller, or the full stack based on a `u8` value
- Added convinience methods in contract API to call into the newly added FFI method
- Fixed the add bid wasm to make the min and max delegation to be optional CLI style arguments as opposed to rust enum style Option

### CODE REVIEW

**Comment by darthsiroftardis** [comment]
bors try

**Comment by darthsiroftardis** [comment]
bors try

**Review by mpapierski — APPROVED** [review]

**Comment by darthsiroftardis** [comment]
bors try

**Comment by darthsiroftardis** [comment]
bors try

**Pull request merged**
