### PR TITLE
RocksDb Support -> feat-rocksdb

### LINKED ISSUE #2481: Add on-disk file size checks to WasmTestBuilder
We need to watch data.lmdb and it's growth, so we should add the capacity to check the on-disk size of lmdb during a test. This would be useful to know, for example, the size growth after N transfers, purses, auction steps with N delegators, etc.

### PR DESCRIPTION
**Pull request by dwerner**

### CODE REVIEW

**Comment by dwerner** [comment]
Repointing this PR at feat-rocksdb

**Comment by dwerner** [comment]
bors try

**Review by Fraser999 — APPROVED** [review]

**Comment by dwerner** [comment]
bors merge

**Comment by dwerner** [comment]
bors merge

**Comment by dwerner** [comment]
bors merge

**Pull request merged**
