### PR TITLE
Bring feat-2.0 up to date with dev since `a3aefaa`

### PR DESCRIPTION
**Pull request by georgepisaltu**
This PR brings all recent commits since https://github.com/casper-network/casper-node/commit/a3aefaa13cb5b5006cf253f259b8abdf4c526996 from the dev branch to the feat-2.0 branch.

Merge had no conflicts.

### CODE REVIEW

**Review by goral09 — DISMISSED** [review]
> Merge had no conflicts

If you say so :)

**Comment by goral09** [comment]
> 
> Merge had no conflicts.

For some reason though, compilation failed. Seems like you're still using an `InMemLmdb` somewhere

**Comment by georgepisaltu** [comment]
> > Merge had no conflicts
> 
> If you say so :)

I just redid the merge and again, there are no conflicts when merging with dev. I'm just doing `git merge upstream/dev`, is this not enough? I also checked with `git status` that there are no conflicts after the merge.

**Comment by georgepisaltu** [comment]
> > Merge had no conflicts.
> 
> For some reason though, compilation failed. Seems like you're still using an `InMemLmdb` somewhere

I ran `cargo test --no-run` and indeed the tests are using `InMemoryWasmTestBuilder` in `execution_engine_testing/tests/src/test/regression/gh_3097.rs` and `execution_engine_testing/tests/src/test/contract_api/dictionary.rs`. So this should probably need to be addressed in the merge commit.

**Comment by georgepisaltu** [comment]
Closed in favor of https://github.com/casper-network/casper-node/pull/3180

**Pull request closed without merging**
