### PR TITLE
Fix version string

### LINKED ISSUE #4697: Sidecar and Casper Node Connectivity Error due to version
Sidecar and Casper Node Connectivity Error

casper-node: feat-2.0 (8a56be6eec9ecd3f1a06c59c7b32dd9b5c631b7c)
casper-sidecar: feat-2.0 (a3533ba0d127afcf373979e4c284f2f20a903916)
:red_circle: Issue: Sidecar and Casper Node Connectivity Error
new casper-node build name and version error
cladmin@casper-node-ajith-condor-small-pv-0:~$ /var/lib/casper/bin/2_0_1/casper-node --version
casper-node 2.0.0@8A56BE6EE
cladmin@casper-node-ajith-condor-small-pv-0:~$ sudo /opt/casper-sidecar/casper-sidecar -p /opt/casper-sidecar/config-sidecar.toml 
2024-05-02T23:05:27.307658Z  INFO casper_rpc_sidecar::rpcs: started JSON RPC server; address=0.0.0.0:7777
2024-05-02T23:05:27.307713Z  INFO casper_rpc_sidecar::rpcs: started speculative execution server; address=0.0.0.0:7778
2024-05-02T23:05:27.320915Z ERROR casper_event_listener: Error fetching metadata (for 127.0.0.1): failed parsing build version from '2.0.0@8A56BE6EE': invalid digit found in string
2024-05-02T23:05:29.333044Z ERROR casper_event_listener: Error fetching metadata (for 127.0.0.1): failed parsing build version from '2.0.0@8A56BE6EE': invalid digit found in string
2024-05-02T23:05:31.345134Z ERROR casper_event_listener: Error fetching metadata (for 127.0.0.1): failed parsing build version from '2.0.0@8A56BE6EE': invalid digit found in string
2024-05-02T23:05:33.357943Z ERROR casper_event_listener: Error fetching metadata (for 127.0.0.1): failed parsing build version from '2.0.0@8A56BE6EE': invalid digit found in string
2024-05-02T23:05:35.373724Z ERROR casper_event_listener: Error fetching metadata (for 127.0.0.1): failed parsing build version from '2.0.0@8A56BE6EE': invalid digit found in string
2024-05-02T23:05:35.373784Z ERROR casper_event_sidecar: Disconnected from 127.0.0.1. Reason: Max connection attempts reached
2024-05-02T23:05:35.373871Z ERROR casper_event_sidecar::event_stream_server::http_server: Trying to buffer data without an api version observed beforehand
Error: Error running component 'sse_event_server': Connected node(s) are unavailable

6 replies

Jacek Malec
  3 days ago
I think what's happened here is that the version format has changed from
casper-node 2.0.0-8A56BE6EE // release 
casper-node 2.0.0-8A56BE6EE@debug // debug
to
casper-node 2.0.0@8A56BE6EE // release
casper-node 2.0.0@8A56BE6EE // debug

Jacek Malec
  3 days ago
because the way the node formats versions is this
{CARGO_PKG_VERSION}-{VERGEN_GIT_SHA}@{NODE_BUILD_PROFILE}

Jacek Malec
  3 days ago
@Zach
 I think this is related to the vergen change, the formatting in here will need to be adjusted to maintain the old format
https://github.com/casper-network/casper-node/blob/feat-2.0/node/src/lib.rs#L78-L100
it might also make sense to expose two separate variables, one for GIT_SHA and one for BUILD_PROFIE to keep things as they were
lib.rs
fn version_string(color: bool) -> String {
    let mut version = env!("CARGO_PKG_VERSION").to_string();
    if let Ok(git_sha) = env::var("VERGEN_GIT_SHA") {
        version = format!("{}-{}", version, git_sha);
    } else {
        warn!(
            "vergen env var unavailable, casper-node build version will not include git short hash"
        );
    }

    // Add a `@DEBUG` (or similar) tag to release string on non-release builds.
    if env!("NODE_BUILD_PROFILE") != "release" {
        version += "@";
        let profile = env!("NODE_BUILD_PROFILE").to_uppercase();
        version.push_str(&if color {
            Red.paint(&profile).to_string()
        } else {
            profile
        });
    }

    version

### PR DESCRIPTION
**Pull request by jacek-casper**
After https://github.com/casper-network/casper-node/pull/4674, the version format of the node has changed from
```
casper-node 2.0.0-8A56BE6EE // release 
casper-node 2.0.0-8A56BE6EE@DEBUG // debug
```
to
```
casper-node 2.0.0@8A56BE6EE // release
casper-node 2.0.0@8A56BE6EE // debug
```

This has caused some issues downstream where we attempt to parse this version string (the sidecar). This change aligns the behavior with what it used to do. I've also added a test to ensure we don't break it by accident in the future, although we can't cover build script issues in the unit test.

### CODE REVIEW

**Review by zacshowa — APPROVED** [review]
LGTM

**Comment by devendran-m** [comment]
Related Issue #4697

**Pull request merged**
