### PR TITLE
ee/contract-messages: use `EntityAddr` for messages

### PR DESCRIPTION
**Pull request by alsrdn**
Replace `AddressableEntityHash` with `EntityAddr` in contract messages types.

### CODE REVIEW

**Review by EdHastingsCasperAssociation — APPROVED** [review]

**Comment by alsrdn** [comment]
bors merge

**Comment by alsrdn** [comment]
bors merge

**Comment by alsrdn** [comment]
bors single on

**Comment by alsrdn** [comment]
bors merge

**Pull request merged**
