### PR TITLE
Data extensibility block conversion

### PR DESCRIPTION
**Pull request by rafal-ch**
This is based on the work from @alsrdn here: https://github.com/casper-network/casper-node/pull/4200

It adds few commits to address the original review comments.

Fixes: https://github.com/casper-network/casper-node/issues/4176
Fixes: https://github.com/casper-network/casper-node/issues/4178

### CODE REVIEW

**Review by Fraser999 — APPROVED** [review]

**Review by EdHastingsCasperAssociation — CHANGES_REQUESTED** [review]
i'd like to discuss this before it merges

**Comment by rafal-ch** [comment]
As per discussion, the requested changes boil down to rename of the functions that deal with `block_v2` structs - these functions should be renamed to **not** include the `v2` in their names.

**Comment by rafal-ch** [comment]
~This waits until the `dev` to `feat-2.0` merge is concluded.~

Alternatively, we might address the comment and merge this to feature branch without the rustsec fix for now.

**Comment by rafal-ch** [comment]
As per the discussion with @Fraser999 and @alsrdn 

1. We plan to leave only a single function related to the extensible datatypes, for example: we'll leave just the `get_block()`
2. This function will always return the enum with version variants
3. While this may create some burden on the callers, there should not be that many different call-sites for this to actually be a huge issue (also, if this eventually becomes an issue, we may always decide to provide additional utility function like `fn get_most_recent_block_version()`, but these should be decided case-by-case).

The above refactor will be delivered as part of https://github.com/casper-network/casper-node/issues/4177, which is the data extensibility work planned for next sprint.

This PR will be merged to the feature branch (`feat-data-extensibility`) as is.
Then we'll merge `feat-data-extensibility` to `feat-2.0` (separate ticket will be requested) because we'd like to unlock work that requires extensible block.
Then, next PRs for data extensibility will go directly into `feat-2.0`.

cc: @EdHastingsCasperAssociation if this sounds ok, please unlock the merge.

**Review by EdHastingsCasperAssociation — APPROVED** [review]

**Pull request merged**
