### PR TITLE
Fix failing test failures on `feat-1.6`

### PR DESCRIPTION
**Pull request by marc-casperlabs**
This PR hopefully gets the `feat-1.6` branch green again by fixing a few bugs and lints.

### CODE REVIEW

**Review by Fraser999 — APPROVED** [review]

**Review by alsrdn — APPROVED** [review]

**Comment by Fraser999** [comment]
bors merge

**Review by rafal-ch — APPROVED** [review]
LGTM :+1:

**Comment by marc-casperlabs** [comment]
@Fraser999 @rafal-ch I had to add some workarounds in b70694e1b, as a full refactoring/fix is too big at the moment. This should :crossed_fingers: get bors-run nctl tests to work.

**Comment by marc-casperlabs** [comment]
bors retry

**Pull request merged**
