### PR TITLE
Fix `client.sh` nighly test

### PR DESCRIPTION
**Pull request by rafal-ch**
This PR updates the `client.sh` test so it's passing with the 2.0 node and casper client built from `feat-track-node-2.0`.

There will be a follow-up PRs, in particular:
1. uncomment the code in `test_get_dictionary_item` test after other PRs mentioned in the code comments are merged
2. prepare a way to test the new clinet with legacy data (blocks, accounts) and then re-enable `test_get_account`
3. get-entity test needs to be updated to test for more variants than just Account kind

### CODE REVIEW

**Review by jacek-casper — APPROVED** [review]

**Review by Fraser999 — APPROVED** [review]

**Review by alsrdn — APPROVED** [review]

**Comment by rafal-ch** [comment]
The flaky test issue has been solved here: https://github.com/casper-network/casper-node/pull/4597

**Pull request merged**
