### PR TITLE
Add changelog entry for shutdown_on_standstill option.

### PR DESCRIPTION
**Pull request by afck**
Add a changelog entry for https://github.com/casper-network/casper-node/pull/1681.

### CODE REVIEW

**Review by goral09 — APPROVED** [review]
I think you could add a couple more words around what _stalled_ means but it's not a blocker, more like an opinion.

**Review by fizyk20 — APPROVED** [review]

**Comment by afck** [comment]
Yes, I'm not sure how much detail should go into the changelog. Maybe:
```
* Don't shut down anymore if consensus stops making progress.
  This used to be the default so the node would restart and possibly be better connected.
  To re-enable it, set the config option `shutdown_on_standstill = true` in `[consensus.highway]`.
```

**Comment by goral09** [comment]
Personally, I would give enough information in the changelog so that a person not involved in the project can understand (more or less) what the change was about.

**Comment by afck** [comment]
Just taked to @Fraser999 and he likes the shorter one, so I'd merge it for now.
There's also a little bit more detail in the `config-example.toml`. Maybe I should expand that instead?

**Comment by afck** [comment]
bors merge

**Comment by goral09** [comment]
> Just taked to @Fraser999 and he likes the shorter one, so I'd merge it for now.
> There's also a little bit more detail in the `config-example.toml`. Maybe I should expand that instead?

I think the target audience of the changelog shouldn't have to read the code to understand the change. The changelog isn't for devs, it's for managers, people using the project – validators making a decision whether they want to use the new binary, users determining whether they can use the new version of the client, etc.

**Comment by afck** [comment]
Sure, but "stalled", "no progres in consensus", "no protocol state change" all would require a lot more explanation to really give any additional information; much more than what fits in a changelog, I think. Do you have a suggestion for the entry?

**Pull request merged**
