### PR TITLE
Move client to its own repo

### LINKED ISSUE #2287: move casper-client to own repo

### PR DESCRIPTION
**Pull request by Fraser999**
This removes the client crate from the casper-node monorepo.  Its new home is https://github.com/casper-ecosystem/casper-client-rs.

Closes #2287.

### CODE REVIEW

**Comment by Fraser999** [comment]
bors try

**Comment by Fraser999** [comment]
bors try

**Review by darthsiroftardis — APPROVED** [review]

**Review by TomVasile — APPROVED** [review]
looked good locally, lgtm!

**Pull request merged**
