### PR TITLE
Add changelogs to published projects

### LINKED ISSUE #1541: Add changelogs to each published crate
Provide entries for each published version after and including 1.0.0, and an `Unreleased` section at the top.

### PR DESCRIPTION
**Pull request by Fraser999**
This adds changelogs for all published projects, with details of changes from versions 1.0.0 onward.

Closes #1541.

### CODE REVIEW

**Comment by xcthulhu** [comment]
Can we add a [pull_request_template.md][1] which includes a checkbox updating the changelog?

[1]: https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository

**Review by nilz3ro — APPROVED** [review]
lgtm, I also think that adding a PR template would be nice, it should help us remember to update the docs as well when we make changes to things that may affect users.

**Comment by Fraser999** [comment]
bors merge

**Comment by Fraser999** [comment]
bors merge

**Pull request merged**
