### PR TITLE
Change loglevel at runtime

### LINKED ISSUE #3369: Allow for changing the log level at runtime
The diagnostics port should allow changing the log level at runtime. For this, a new command should be added which should be equivalent to setting the loglevel through an ENVVAR. Example:

`set-loglevel INFO,casper_node::components::network=DEBUG`

### PR DESCRIPTION
**Pull request by marc-casperlabs**
Closes #3369.

Allows changing the log level at runtime through the diagnostics port.

### CODE REVIEW

**Review by rafal-ch — APPROVED** [review]
LGTM :+1: 

I have one nit, which is not related to this PR. Sending a line that cannot be parsed into `Command` (that includes an empty line) results in an `ERR` message, which is not dangerous, but just looks a bit bad :)
```
magister@zacisze:~$ socat - unix:/home/magister/Casper/casper-node/utils/nctl/assets/net-1/nodes/node-1/config/1_0_0/debug.socket

ERR  casper-node 1.4.8
Action to perform

USAGE:
    casper-diagnostics-port <SUBCOMMAND>
    .....
```

```
magister@zacisze:~$ socat - unix:/home/magister/Casper/casper-node/utils/nctl/assets/net-1/nodes/node-1/config/1_0_0/debug.socket

-h
ERR  casper-node 1.4.8
Action to perform

USAGE:
    casper-diagnostics-port <SUBCOMMAND>
    .....
```

I think we could consider improving `process_line()`.

**Comment by marc-casperlabs** [comment]
> I have one nit, which is not related to this PR. Sending a line that cannot be parsed into `Command` (that includes an empty line) results in an `ERR` message, which is not dangerous, but just looks a bit bad :)

That's actually intentional. When using it non-interactively, you will always get back exactly one response indicating the outcome of your operation for every line you sent. I'd rather keep it this way!

The response can be disabled entirely by setting quiet mode.

**Comment by marc-casperlabs** [comment]
bors retry

**Review by EdHastingsCasperAssociation — APPROVED** [review]

**Pull request merged**
