### PR TITLE
Better Error:try_from tests

### PR DESCRIPTION
**Pull request by xcthulhu**

### CODE REVIEW

**Review by mpapierski — APPROVED** [review]
Looks good

**Review by afck — APPROVED** [review]

**Comment by xcthulhu** [comment]
bors merge

**Comment by xcthulhu** [comment]
bors cancel

**Comment by xcthulhu** [comment]
bors merge

**Comment by afck** [comment]
bors merge

**Comment by xcthulhu** [comment]
Rebasing, zapping `Cargo.lock` and trying again...

**Comment by xcthulhu** [comment]
bors merge

**Pull request merged**
