### PR TITLE
Prevent stray `accounts.toml` files from breaking upgrades

### PR DESCRIPTION
**Pull request by fizyk20**
The rewards calculation used to take the validators from `accounts.toml` when writing zero rewards to validators at genesis or at an upgrade point. This is now just replaced with an empty map, which has the same effect and doesn't depend on external data.

### CODE REVIEW

**Review by alsrdn — APPROVED** [review]
LGTM

**Review by EdHastingsCasperAssociation — APPROVED** [review]

**Comment by fizyk20** [comment]
bors merge

**Pull request merged**
