### PR TITLE
Correct documentation about USR1 dumps

### LINKED ISSUE #2613: Is kill -USR1 $NODE_PID still working?
1. Please clarify "working directory" in the README.md for the queue_dump.json file

2. Out of curiosity I tried the command also mentioned in the README.md:
```
kill -USR1 $NODE_PID
```

Exactly nothing happened. I also couldn't find the queue_dump.json file:
```
find / -name queue_dump.json
```

The node is in the mainnet but not validating, no bid, not bonded -> could that be the reason?

3. I also just tried the following command out of curiosity:
```
kill -USR2 $NODE_PID
```

-> That command crashed the node causing a trie-state check etc.

I don't know the Un*x process and signal handling good enough but the node shouldn't just crash when it receives an unknown signal I guess but just ignore it as long as it isn't a -9/SIGKILL which can't be ignored anyway IIRC.

I also saw there is a debug console coming so maybe that is fixed there already or should be tested and improved to not crash so easily.

### PR DESCRIPTION
**Pull request by marc-casperlabs**
They have been removed in favor of the diagnostics port.

Closes #2613.

### CODE REVIEW

**Review by rafal-ch — APPROVED** [review]
LGTM :+1:

**Review by Fraser999 — APPROVED** [review]

**Comment by marc-casperlabs** [comment]
bors retry

**Comment by marc-casperlabs** [comment]
bors merge

**Pull request merged**
