### PR TITLE
Unify account migration paths

### PR DESCRIPTION
**Pull request by darthsiroftardis**
CHANGELOG:

- Fixed bug in migration logic that would sometimes cause a pseudo random hash to be used as the EntityAddr instead of the account hash when an account is migrated

### CODE REVIEW

**Review by alsrdn — APPROVED** [review]
LGTM, good catch!

**Comment by darthsiroftardis** [comment]
bors try

**Comment by rafal-ch** [comment]
bors try

**Comment by darthsiroftardis** [comment]
bors try

**Comment by darthsiroftardis** [comment]
bors try

**Comment by cspramit** [comment]
As discussed with Karan - closing this infavor of https://github.com/casper-network/casper-node/pull/4745

**Pull request closed without merging**
