### PR TITLE
Increased `DICTIONARY_ITEM_KEY_MAX_LENGTH`

### LINKED ISSUE #2157: Dictionary keys' max length should be increased
Currently the `DICTIONARY_ITEM_KEY_MAX_LENGTH` is set to 64.  This is too short to be useful in some cases where it would be convenient to use our formatted-hex format for various types.

The const should be updated to 128.

### PR DESCRIPTION
**Pull request by luis-casper**
Not sure why Drone is failing.

### CODE REVIEW

**Comment by goral09** [comment]
> Not sure why Drone is failing.

Can you merge `dev` into you branch and update `Cargo.lock` file?

**Comment by luis-casper** [comment]
I mean, I am one commit ahead of upstream/dev with only one minor change.

**Comment by luis-casper** [comment]
bors try

**Review by mpapierski — APPROVED** [review]

**Review by dwerner — APPROVED** [review]

**Pull request merged**
