### PR TITLE
Port the changes related to handling of unbonds in `global-state-update-gen` to `feat-2.0`

### PR DESCRIPTION
**Pull request by fizyk20**
This ports the changes made in #4828 to `feat-2.0`.

### CODE REVIEW

**Review by EdHastingsCasperAssociation — APPROVED** [review]

**Comment by fizyk20** [comment]
`reactor::main_reactor::tests::node_should_rejoin_after_ejection` seems to be flaky. It passed for me twice locally, but I can reproduce the failure with the given seed (`CL_TEST_SEED=08f498218291e7059a207a4a4ff0a78a`). I'll try to merge this and fix the test in a separate PR.

**Pull request merged**
